---
- name: Ensure necessary Microsoft features are installed
  ansible.windows.win_feature:
    name: "{{ item }}"
    state: present
  with_items:
  # Available features can be listed using Get-WindowsFeature
  - AD-Domain-Services
  - RSAT-AD-AdminCenter
  - RSAT-ADDS-Tools

- name: Ensure domain is created
  win_domain:
    dns_domain_name: "{{ domain.dns_name }}"
    safe_mode_password: "TODO"
  register: domain_creation

- name: Reboot if domain was just created
  ansible.windows.win_reboot:
  when: domain_creation.reboot_required

- name: Ensure domain controllers are promoted
  win_domain_controller:
    dns_domain_name: "{{ domain.dns_name }}"
    domain_admin_user: "{{ domain.initial_domain_admin.username }}@{{ domain.dns_name }}"
    domain_admin_password: "{{ domain.initial_domain_admin.password }}"
    safe_mode_password: "TODO"
    state: domain_controller
    log_path: C:\Windows\Temp\promotion.txt
  register: dc_promotion

- name: Reboot if server was just promoted to a domain controller
  win_reboot: {}
  when: dc_promotion.reboot_required

- name: Ensure xActiveDirectory PS DSC module is installed
  win_psmodule:
    name: xActiveDirectory
    state: present

- name: Wait for domain to be available
  win_dsc:
    resource_name: xWaitForADDomain
    DomainName: "{{ domain.dns_name }}"
    RetryCount: 100
    RetryIntervalSec: 10
  when: packer is not defined

- name: Include domain configuration file
  include_vars:
    file: ../../../domain.yml
    name: domain

- name: Set domain root path (e.g. DC=xtof,DC=lab)
  set_fact:
    # e.g. DC=xtof,DC=lab
    domain_root_path: DC={{ domain.dns_name.split('.') | join(',DC=') }}

- name: Read credentials from domain configuration file
  set_fact:
    ansible_user: "{{ domain.initial_domain_admin.username }}"
    ansible_password: "{{ domain.initial_domain_admin.password }}"
  when: "packer is not defined"

- name: Ensure domain is available
  win_dsc:
    resource_name: xWaitForADDomain
    DomainName: "{{ domain.dns_name }}"
    RetryCount: 100
    RetryIntervalSec: 10
  when: packer is not defined # TODO

- name: Set a weak password policy
  win_command: powershell.exe -
  args:
    stdin: "Set-ADDefaultDomainPasswordPolicy -MinPasswordLength 1 -ComplexityEnabled $False -Identity {{ domain.dns_name }}"

- name: Ensure domain users exist
  win_domain_user:
    name: "{{ item.username }}"
    password: "{{ item.password | default(item.username) }}"
    path: "{{ item.OU | default('CN=Users') }},{{ domain_root_path }}"
    enabled: yes
  with_items: "{{ domain.users }}"

- name: Group memberships
  win_domain_group_membership:
    name: "{{ item.dn }},{{ domain_root_path }}"
    members: "{{ item.members }}"
  with_items: "{{ domain.groups }}"

- name: Ensure OUs exist
  win_dsc:
    resource_name: xADOrganizationalUnit
    Name: "{{ item.split(',')[0].split('=')[1] }}" # CN=xxx,.. => keep 'xxx'
    Path: "{{ item.split(',') | reject('search', item.split(',')[0]) | map('regex_replace', '(.+)', '\\1,') | join('') }}{{ domain_root_path }}"
    ProtectedFromAccidentalDeletion: no
  with_items: "{{ domain.organizational_units }}"

- name: Ensure domain users exist
  win_domain_user:
    name: "{{ item.username }}"
    password: "{{ item.password | default(item.username) }}"
    path: "{{ item.OU | default('CN=Users') }},{{ domain_root_path }}"
    enabled: yes
  with_items: "{{ domain.users }}"

- name: Group memberships
  win_domain_group_membership:
    name: "{{ item.dn }},{{ domain_root_path }}"
    members: "{{ item.members }}"
  with_items: "{{ domain.groups }}"
