---
- name: Include domain configuration file
  include_vars:
    file: ../../../domain.yml
    name: domain
  tags: common

- name: Read credentials from domain configuration file
  set_fact:
    ansible_user: "{{ domain.initial_domain_admin.username }}"
    ansible_password: "{{ domain.initial_domain_admin.password }}"
  when: "packer is not defined"
  tags: common

- include_tasks: base.yml
  tags: base


    