plugin: azure_rm
auth_source: cli

include_vm_resource_groups:
- ad-vuln-lab
conditional_groups:
  domain_controllers: "tags.kind == 'domain-controller'"
  workstations: "tags.kind == 'workstation'"
keyed_groups:
- prefix: tag
  key: tags